### PR TITLE
DecaStation

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

DecaStation, a small station designed to facilitate your autism forting needs without being cumbersome to work with. DecaStation is intentionally low maintenance, using a solar and turbine for power, instead of the alternatives such as a supermatter engine which is prone to destroying half the station if fucked up. Most areas which experience heavy traffic such as medbay and the production lab are given toggleable shutters to allow free passage if needed.

## Why It's Good For The Game

DecaStation is perfect for low-pop servers like ours.

## Changelog
:cl:
add: DecaStation
/:cl:

### CODE REVIEW

**Comment by park66665** [comment]
1. You should use `/obj/machinery/atmospherics/components/trinary/mixer/airmix/inverse` instead of `/obj/machinery/atmospherics/components/trinary/mixer/airmix` for airmix mixer because currently that mixer mixes 71% Oxygen and 29% Nitrogen.
2. You flipped the dual port air vent of engineering external airlock so it currently tries to draw air from scrubber's network -- and can't cycle to interior.

**Comment by jbox144** [comment]
easy fixes

**Comment by park66665** [comment]
absolutely

**Comment by park66665** [comment]
I briefly checked the atmos
1. Lack of pipe at 47,64
2. Lack of pipe at 65,64
3. Unconnected vent pump at 93, 85
4. Unconnected air scrubber at 91, 85
5. Pipes overlapping at 29, 92 and 33, 92
6. ...and an almost empty atmos department?

**Comment by jbox144** [comment]
>     6. ...and an almost empty atmos department?

it's intentionally empty for building whatever you want in the middle.

**Comment by park66665** [comment]
> it's intentionally empty for building whatever you want in the middle.

Oh, okay.

**Pull request merged**
